In [79]:
from pandas import read_csv
import seaborn as sns
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2,f_regression,f_classif
dataframe=sns.load_dataset('tips')
dataframe

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [81]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
dataframe['sex']=lb.fit_transform(dataframe['sex'])
dataframe['smoker']=lb.fit_transform(dataframe['smoker'])
dataframe['day']=lb.fit_transform(dataframe['day'])
dataframe['time']=lb.fit_transform(dataframe['time'])

In [83]:
X = dataframe.drop('tip',axis=1)
Y = dataframe.tip

In [85]:
X

total_bill  sex  smoker  day  time  size
0         16.99    0       0    2     0     2
1         10.34    1       0    2     0     3
2         21.01    1       0    2     0     3
3         23.68    1       0    2     0     2
4         24.59    0       0    2     0     4
..          ...  ...     ...  ...   ...   ...
239       29.03    1       0    1     0     3
240       27.18    0       1    1     0     2
241       22.67    1       1    1     0     2
242       17.82    1       0    1     0     2
243       18.78    0       0    3     0     2

[244 rows x 6 columns]

In [87]:
test = SelectKBest(score_func=f_regression, k=4).fit(X,Y)
test

SelectKBest(k=4, score_func=<function f_regression at 0x000001A70C636660>)

In [89]:
dataframe.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [91]:
test.scores_

array([2.03357723e+02, 1.92615456e+00, 8.50601355e-03, 3.22744400e-02,
       3.63381548e+00, 7.61754260e+01])

In [93]:
np.round(test.pvalues_,2)

array([0.  , 0.17, 0.93, 0.86, 0.06, 0.  ])

In [95]:
np.round(test.scores_,7)

array([2.03357723e+02, 1.92615460e+00, 8.50600000e-03, 3.22744000e-02,
       3.63381550e+00, 7.61754260e+01])

In [97]:
np.round(10.4555679,2)

10.46

In [99]:
np.round(test.pvalues_,3)

array([0.   , 0.166, 0.927, 0.858, 0.058, 0.   ])

In [101]:
test.get_feature_names_out()

array(['total_bill', 'sex', 'time', 'size'], dtype=object)

In [103]:
dataframe.columns[np.where(test.pvalues_<0.05)]

Index(['total_bill', 'time'], dtype='object')

In [105]:
#For regression: f_regression, mutual_info_regression
#For classification: chi2, f_classif, mutual_info_columns

In [109]:
df=sns.load_dataset('iris')

In [111]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [113]:
df['species']=lb.fit_transform(df['species'])

In [115]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [119]:
x=df.iloc[:,0:4]
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [123]:
y=df['species']
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int32

In [125]:
sel=SelectKBest(score_func=f_classif,k=2).fit(x,y)
sel

SelectKBest(k=2)

In [127]:
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [129]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int32

In [133]:
sel.scores_

array([ 119.26450218,   49.16004009, 1180.16118225,  960.0071468 ])

In [135]:
sel.pvalues_

array([1.66966919e-31, 4.49201713e-17, 2.85677661e-91, 4.16944584e-85])

In [139]:
df.columns[np.where(sel.get_support(indices=True))]

Index(['sepal_length', 'sepal_width'], dtype='object')

In [143]:
sel.get_feature_names_out()

array(['petal_length', 'petal_width'], dtype=object)

# Recursive Feature Elmination